title: Junteng Liu
authors:
  - Junteng Liu

description: Junteng Liu's personal homepage. First-year PhD candidate at HKUST NLP Group.

# The base hostname & protocol for your site, e.g. http://example.com
baseurl: /LJT-Homepage/
url: https://sunwills.github.io/

# Site settings
# title is already defined above
author: Junteng Liu

# Theme
remote_theme: academicpages/academicpages.github.io

# Footer text
footer_text: "Powered by <a href=\"https://pages.github.com\" target=\"_blank\">GitHub Pages</a>"

# Site theme configuration
markdown: kramdown
remote_theme: academicpages/academicpages.github.io

# Social links
social:
  type: "Person"
  name: "Junteng Liu"
  url: "https://sunwills.github.io/LJT-Homepage/"
  email: jliugi@connect.ust.hk
  github: Vicent0205
  googlescholar: https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
  twitter: junteng88716710

# Site collections
collections:
  pages:
    output: true
  posts:
    output: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author_profile: true
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jemoji
